--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirito/Pictures/wallpapers/miku.png"

-- Special
background="#101315"
foreground="#e4e1e3"
cursor="#e4e1e3"

-- Colors
color0="#101315"
color1="#A39CA2"
color2="#8EABB7"
color3="#D1AFB0"
color4="#A0B7C4"
color5="#D2BFC1"
color6="#AFC6D0"
color7="#e4e1e3"
color8="#9f9d9e"
color9="#A39CA2"
color10="#8EABB7"
color11="#D1AFB0"
color12="#A0B7C4"
color13="#D2BFC1"
color14="#AFC6D0"
color15="#e4e1e3"
