foreground   #c9d9e5
background   #090306
cursor       #c9d9e5

color0       #090306
color8       #8c97a0
color1       #2D67A1
color9       #2D67A1
color2       #BB7784
color10      #BB7784
color3       #0DAFD9
color11      #0DAFD9
color4       #FDD493
color12      #57A9D2
color5       #FBAB9C
color13      #FBAB9C
color6       #57A9D2
color14      #FDD493
color7       #c9d9e5
color15      #c9d9e5
