# Shell variables
# Generated by 'wal'
wallpaper='/home/kirito/Pictures/wallpapers/miku.png'

# Special
background='#101315'
foreground='#e4e1e3'
cursor='#e4e1e3'

# Colors
color0='#101315'
color1='#A39CA2'
color2='#8EABB7'
color3='#D1AFB0'
color4='#A0B7C4'
color5='#D2BFC1'
color6='#AFC6D0'
color7='#e4e1e3'
color8='#9f9d9e'
color9='#A39CA2'
color10='#8EABB7'
color11='#D1AFB0'
color12='#A0B7C4'
color13='#D2BFC1'
color14='#AFC6D0'
color15='#e4e1e3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
