--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirito/Pictures/wallpapers/persona3.png"

-- Special
background="#090306"
foreground="#c9d9e5"
cursor="#c9d9e5"

-- Colors
color0="#090306"
color1="#2D67A1"
color2="#BB7784"
color3="#0DAFD9"
color4="#57A9D2"
color5="#FBAB9C"
color6="#FDD493"
color7="#c9d9e5"
color8="#8c97a0"
color9="#2D67A1"
color10="#BB7784"
color11="#0DAFD9"
color12="#57A9D2"
color13="#FBAB9C"
color14="#FDD493"
color15="#c9d9e5"
